name: open_copyright_platform
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  bloc: ^0.13.0
  flutter_bloc: ^0.13.0
  meta: ^1.1.6
  equatable: ^0.2.0
  json_serializable: ^3.0.0
  flutter_slidable: "^0.5.3"
  rails_api_connection:
    path: rails_api_connection
  flutter_secure_storage: ^3.2.0
  http: ^0.12.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/