name: rails_api_connection
description: Most of api connection throught rails will be here.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  meta: ^1.1.6
  flutter_secure_storage: ^3.2.0
  http: ^0.12.0+1
  equatable: ^0.2.0
  json_serializable: ^3.0.0
